server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: rent-service
    public-prefix-path: ${RENT_SERVICE_PUBLIC_URL_PREFIX:/ru.dmsmirnov.rent.api/rent}
    private-prefix-path: ${RENT_SERVICE_PRIVATE_URL_PREFIX:/rent}
  datasource:
    url: ${RENT_SERVICE_DB_JDBC_URL:jdbc:postgresql://localhost:5432/rent_service}
    username: ${RENT_SERVICE_DB_USERNAME:postgres}
    password: ${RENT_SERVICE_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: ${SPRING_DATASOURCE_HIKARI_MAXLIFETIME:1800000}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${RENT_SERVICE_DB_SCHEMA:rent_service}
        jdbc.lob.non_contextual_creation: true
    open-in-view: false
    show-sql: ${RENT_SERVICE_JPA_SHOW_SQL:false}
  liquibase:
    enabled: ${RENT_SERVICE_LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/master.xml
    default-schema: ${RENT_SERVICE_DB_SCHEMA:rent_service}
  data:
    redis:
      host: ${RENT_SERVICE_REDIS_HOST:localhost}
      port: ${RENT_SERVICE_REDIS_PORT:6379}
      password: ${RENT_SERVICE_REDIS_PASSWORD:}
  cache:
    type: ${RENT_SERVICE_CACHE_TYPE:redis} #simple
    redis:
      time-to-live: ${RENT_SERVICE_CACHE_TTL:600000}

info:
  application:
    version: ${APP_VERSION:0.0.1-SNAPSHOT}

logging:
  pattern:
    console: "${LOG_CONSOLE_PATTERN:%d{yyyy-MM-dd HH:mm:ss.SSS} %+5level --- [%+15.15thread] %-40.40logger{36} : %msg%n}"
  level:
    ROOT: INFO
    ru.neuroland.mnemonica.RENT: ${RENT_SERVICE_LOG_LEVEL:INFO}
    org.springframework: ${RENT_SERVICE_LOG_LEVEL_SPRING:INFO}

springdoc:
  packages-to-scan: ru.dmsmirnov.rent.api.controller.rest
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha

rent:
  admin:
    stub-enabled: ${RENT_ADMIN_STUB_ENABLED:true}
